name = "Groebner"
uuid = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
authors = ["sumiya11"]
version = "0.5.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnsafeAtomics = "013be700-e6cd-48c3-b4a1-df204f14c38f"

[compat]
AbstractAlgebra = "0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34"
BenchmarkTools = "1"
Combinatorics = "1"
ExprTools = "0.1"
MultivariatePolynomials = "0.4, 0.5"
PrecompileTools = "1"
PrettyTables = "2"
Primes = "0.5"
SIMD = "3"
TestSetExtensions = "2"
TimerOutputs = "0.5"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["DynamicPolynomials", "BenchmarkTools", "Test", "TestSetExtensions", "Nemo"]
